name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - uses: nrwl/nx-set-shas@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.14.5
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm nx affected --base=origin/main --head=HEAD --target=lint
      - run: pnpm nx affected --base=origin/main --head=HEAD --target=build
